hw-3-1
js-tasks-ru/htmlcss-20230530_dmitry85 pull request #3
Opened 2023-06-11 17:39 UTC by dmitryrg

2023-06-11 17:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-11 20:50 UTC, GSemikozov requested changes

2023-06-11 20:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.header {
описываем блок heder внутри блока button? удалим, это здесь не нужно

2023-06-11 20:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-width: 189px;
не хватает паддингов и font-family

2023-06-11 20:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
opacity: 0.5 + pointer-events: none

2023-06-11 20:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.main__button {
элемент блока main?

2023-06-11 20:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.main__button {
не нужно искать варианты задавать марджины кнопкам

2023-06-12 18:06 UTC, dmitryrg commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
исправил

2023-06-12 18:06 UTC, dmitryrg commented on 03-lection1/01-button/button.css
> +.main__button {
убрал

2023-06-12 18:08 UTC, dmitryrg commented on 03-lection1/01-button/button.css
> +    min-width: 189px;
паддинги добавил, фонт- задан в main.css

2023-06-15 14:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-width: 189px;
font тут наследовать не безопасно, поскольку можно встроить кнопку в аккордион, а там главный шрифт уже не Робота, а Интер ))

2023-06-15 14:50 UTC, GSemikozov requested changes

2023-06-15 14:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-width: 189px;
паддинги в пересчета на пиксели должны быть `15 15 14`

2023-06-15 14:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
это свойство можно удалить

2023-06-18 21:23 UTC, dmitryrg commented on 03-lection1/01-button/button.css
> +    min-width: 189px;
внес правки

2023-06-18 21:25 UTC, dmitryrg commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
курсор убрал

2023-06-19 20:33 UTC, GSemikozov approved these changes

2023-06-19 20:33 UTC, merged