hw-3-2
js-tasks-ru/htmlcss-20230530_dmitry85 pull request #4
Opened 2023-06-11 18:38 UTC by dmitryrg

2023-06-11 18:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-11 18:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-11 20:53 UTC, GSemikozov requested changes

2023-06-11 20:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.header {
лишнее, удалим

2023-06-11 20:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.main__accordion {
лишнее, удалим

2023-06-11 20:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
1. это не аккордион а его секция (верстаем 1 аккордион у которого 3 секции, а не 3 отдельных аккордиона)
2. ограничивать ширину не нужно

2023-06-11 20:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0.33em 0;
а это сколько в px? советую пока использовать px

2023-06-11 20:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 0.33em;
8px?

2023-06-11 20:53 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0.67em 1.33em;
-> px
и также стоит обратить внимание что в состоянии open паддинг снизу будет другой

2023-06-11 20:53 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <p class="accordion__item">Завоз грунта</p>
accordion__item -> accordion__text
все эти параграфы надо завернуть в общий accordion__content

2023-06-12 18:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-12 18:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-13 08:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-14 18:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-14 18:13 UTC, dmitryrg commented on 03-lection1/02-accordion/accordion.css
> +.header {
хедер удалил

2023-06-14 18:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-14 18:15 UTC, dmitryrg commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
сделал 3 секции одного аккордиона
ширину не ограничиваю, аккордион растянулся на весь экран

2023-06-14 18:15 UTC, dmitryrg commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0.33em 0;
везде поменял на рх

2023-06-14 18:16 UTC, dmitryrg commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0.67em 1.33em;
добавил корректировку

2023-06-14 18:16 UTC, dmitryrg commented on 03-lection1/02-accordion/index.html
> +                <p class="accordion__item">Завоз грунта</p>
завернул в  общий accordion__content

2023-06-15 14:55 UTC, GSemikozov requested changes

2023-06-15 14:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 10vh;
марджины на уровне блока не задаем

2023-06-15 14:55 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <p class="accordion__text">Завоз грунта</p>
все `<p>` лучше завернуть в общий `<div class="accordion__content">`

2023-06-15 14:55 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <details class="accordion__content">
accordion__content -> accordion__section

2023-06-15 14:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-bottom: 24px;
справа тоже нужны

2023-06-18 21:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-18 21:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-19 20:34 UTC, GSemikozov requested changes

2023-06-19 20:34 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 10vh;
все марджины из класса блока удаляем

2023-06-19 20:34 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-bottom: 24px;
все еще актуально

2023-06-20 16:46 UTC, dmitryrg commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 10vh;
удалил

2023-06-20 16:46 UTC, dmitryrg commented on 03-lection1/02-accordion/accordion.css
> +    padding-bottom: 24px;
падинги справа добавил

2023-06-22 20:56 UTC, GSemikozov approved these changes

2023-06-22 20:56 UTC, merged