hw-4-1 - histogram
js-tasks-ru/htmlcss-20230530_dmitry85 pull request #6
Opened 2023-06-25 12:26 UTC by dmitryrg

2023-06-25 12:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-25 19:43 UTC, GSemikozov requested changes

2023-06-25 19:43 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
ширину и высоту фиксировать не надо

2023-06-25 19:43 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее

2023-06-25 19:43 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__stripe-container {
здесь уместно задать фиксированную высоту 50px

2023-06-25 19:43 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__stripe-element" style="height: 50px;"></div>
высоту - в процентах

2023-06-25 19:43 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__switch">View all</div>
`<a>`

2023-06-27 14:07 UTC, dmitryrg commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
Убрал flex-direction и justify-content;

2023-06-27 14:07 UTC, dmitryrg commented on 04-lection2/01-histogram/histogram.css
> +.histogram__stripe-container {
задал 50px

2023-06-27 14:14 UTC, dmitryrg commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__stripe-element" style="height: 50px;"></div>
сделал высоту в процентах

2023-06-27 14:15 UTC, dmitryrg commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
если убрать ширину и высоту все плывет
От чего мне брать ширину и высоту ?

2023-06-27 14:17 UTC, dmitryrg commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__switch">View all</div>
поставил на switch тэг а вместо див-а

2023-06-28 17:18 UTC, dmitryrg commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
Ширина задается гистограммой, высота - отступом (маржин) гистограмы от текста

2023-07-21 13:07 UTC, GSemikozov requested changes

2023-07-21 13:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 306px;
лишнее ограничение ширины

2023-07-21 14:44 UTC, GSemikozov approved these changes

2023-07-21 14:44 UTC, merged