hw-4-2 - skeleton
js-tasks-ru/htmlcss-20230530_dmitry85 pull request #7
Opened 2023-06-25 14:59 UTC by dmitryrg

2023-06-25 15:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-25 19:42 UTC, GSemikozov requested changes

2023-06-25 19:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
лишнее ограничение ширины

2023-06-25 19:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: fit-content;
в целом это лишнее свйоство, в нет нет никакого смысл. А в чем особенность fit-content - см [здесь](https://blog.logrocket.com/understanding-min-content-max-content-fit-content-css/)

2023-06-25 19:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle-element-1 {
.skeleton__rectangle-element - общий элемент, а различие по длине - через модификаторы, например .skeleton__rectangle-element_short

2023-06-25 19:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину в процентах

2023-06-25 19:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 20px;
фот и высота задается в общем классе элемента .skeleton__rectangle-element

2023-06-28 17:23 UTC, dmitryrg commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
поменял на фит-контент

2023-06-28 17:23 UTC, dmitryrg commented on 04-lection2/02-skeleton/skeleton.css
> +    height: fit-content;
убрал высоту равную фит-контент

2023-06-28 17:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-28 17:37 UTC, dmitryrg commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle-element-1 {
сделал через модификаторы

2023-06-28 17:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-28 17:38 UTC, dmitryrg commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 20px;
сделал общий класс

2023-06-28 17:39 UTC, dmitryrg commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
А вот с этим не понятно. Если у нас нет ширины в родительском элементе и на него ссылается дочерний, то откуда возьмется длина? Соответствующий вопрос задал в чате Дискорда

2023-07-16 17:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-21 13:05 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширина родителя, если это блочный элемент, по умолчанию 100% (в свою очередь, по своему родителю)

2023-07-21 13:05 UTC, GSemikozov approved these changes

2023-07-21 13:06 UTC, merged